### ISSUE TITLE
Error with build #33

### ISSUE THREAD

**Issue by FourDown** [confuser/Ban-Management#128]
I just updated banmanager to build #33, on boot I'm getting the error below.

```
[10:13:33] [Server thread/INFO]: [BanManager] Enabling BanManager v5.0.0-SNAPSHOT
[10:13:34] [Server thread/INFO]: [BanManager] Loaded 6443 bans into memory
[10:13:34] [Server thread/INFO]: [BanManager] Loaded 68 mutes into memory
[10:13:34] [Server thread/INFO]: [BanManager] Loaded 33 ip bans into memory
[10:13:34] [Server thread/ERROR]: Error occurred while enabling BanManager v5.0.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:444) ~[?:?]
	at me.confuser.banmanager.BanManager.onEnable(BanManager.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:396) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:364) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:319) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:215) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:529) [spigot.jar:git-PaperSpigot-bfc8900-8047b0a]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
```

The plugin remains enabled, however no commands work, also all bans/mutes etc do not work.

**Comment by confuser** [comment]
Thanks for letting me know. Please hold off on the most recent builds until
the external database is complete. I'm just finalising the commands at the
moment. Then I'll drop in a messages refactor I've been working on to make
it much easier to read/modify.

**Comment by FourDown** [comment]
Safe to update to the latest build?

**Comment by confuser** [comment]
It should be yes. Not found any problems yet.

**Comment by FourDown** [comment]
Thanks! :)
