### ISSUE TITLE
WarningActions not working properly / IndexOutOfBounds

### ISSUE THREAD

**Issue by Kakifrucht** [confuser/Ban-Management#131]
Hello,

first off, I love this plugin, please keep it up, thanks alot!

I'm on build No 33, using localDatabase.

WarningActions currently don't seem to work, they are being executed, but the placeholder is not being replaced I guess. It prints "Requesting UUIDs for [player]" in the console.

Also, since I migrated from v4 there are lots of players who have no IP record, so they show 0.0.0.0. I put this IP on the bypass list, and whenever you look somebody up with this IP, it prints an IndexOutOfBoundsException -2.

regards!

**Comment by FourDown** [comment]
https://github.com/confuser/Ban-Management/issues/128

In my ticket here, Confuser recommends not using the latest dev builds.

**Comment by Kakifrucht** [comment]
I checked your ticket, BanManager works perfectly though, it's not the same. These are the only two things I came across.
Also, currently there is not really a choice you have. Should I downgrade to to build 30?

**Comment by FourDown** [comment]
Probably a good idea

**Comment by Kakifrucht** [comment]
Is build 30 stable for you?

**Comment by Kakifrucht** [comment]
WarningActions are working in build 30. The IndexOutOfBounds is not fixed though. This is minor though.

**Comment by EDawg878** [comment]
The warning action replacements weren't working, I've added a patch to this in my pull request #132

**Comment by Kakifrucht** [comment]
The IndexOutOfBound is not fixed though.

**Comment by confuser** [comment]
@Kakifrucht When you say 'look up' what command are you using that gives the error?

**Comment by Kakifrucht** [comment]
I'm referring to /bminfo.

**Comment by confuser** [comment]
@Kakifrucht Can you provide the exact stack trace please?

**Comment by Kakifrucht** [comment]
Yes of course, thought it would be so trivial it wouldn't be necessary:

2015-02-01 17:09:39 [WARN] org.apache.commons.lang.UnhandledException: Plugin BanManager v5.0.0-SNAPSHOT generated an exception while executing task 216757
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:173)
	at java.lang.StringBuilder.setLength(StringBuilder.java:72)
	at me.confuser.banmanager.commands.InfoCommand.playerInfo(InfoCommand.java:101)
	at me.confuser.banmanager.commands.InfoCommand$1.run(InfoCommand.java:50)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by confuser** [comment]
Should be fixed in build 40

**Comment by Kakifrucht** [comment]
Nice thank you!
