### ISSUE TITLE
#33: Error occurred while disabling BanManager

### ISSUE THREAD

**Issue by CurePindal** [confuser/Ban-Management#135]
Error on server shutdown:

[11:43:41] [Server thread/ERROR]: Error occurred while disabling BanManager v5.0.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at me.confuser.banmanager.ormlite.jdbc.JdbcPooledConnectionSource.close(JdbcPooledConnectionSource.java:97) ~[?:?]
	at me.confuser.banmanager.ormlite.jdbc.JdbcConnectionSource.closeQuietly(JdbcConnectionSource.java:152) ~[?:?]
	at me.confuser.banmanager.BanManager.onDisable(BanManager.java:138) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:334) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:430) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:561) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]

**Comment by confuser** [comment]
Was this after your conversion finished?

**Comment by CurePindal** [comment]
Yes, that was the shutdown after the conversion was finished!
