### ISSUE TITLE
bmclear command not functional?

### ISSUE THREAD

**Issue by Theepwner** [confuser/Ban-Management#141]
When using /bmclear, it will show

/bmclear <type> <player>

What exactly does <type> refer to?  I've tried inputting warn, mute, ban, tempmute, etc and nothing happens.  I'm using build 46.

**Comment by confuser** [comment]
It's not implemented yet

**Comment by Theepwner** [comment]
/bmclear it still an issue.

The syntax is /bmclear "type" "player" correct?  Using /bmclear warnings "player" does not work properly.

It will output, "Invalid type, please choose between banrecords, muterecords, kicks or warnings"

Also, I think bmclear in general is not working.  I've tried /bmclear muterecords "player" when they have been muted and it displays "muterecords not found, are you sure they exist?"

Lastly, typing an improper command like "/bmclear warnrecords "player" will just show "warnrecords not found, are you sure they exist?"  I believe it should show the "Invalid type, please choose between banrecords, muterecords, kicks or warnings" message instead.

And just in case you might've made it back to "/bmclear "name"", attempting /bmclear "name"
will give this:

[21:14:19] [Server thread/INFO]: Theepwner issued server command: /bmclear UnchainedMC
[21:14:20] [Craft Scheduler Thread - 131/WARN]: java.sql.SQLException: Cannot call query() on a statement of type DELETE
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at me.confuser.banmanager.ormlite.stmt.Where.checkQueryBuilderMethod(Where.java:607)
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at me.confuser.banmanager.ormlite.stmt.Where.query(Where.java:503)
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at me.confuser.banmanager.commands.ClearCommand$2.run(ClearCommand.java:82)
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:14:20] [Craft Scheduler Thread - 131/WARN]:         at java.lang.Thread.run(Thread.java:745)

Thanks for your work!

**Comment by confuser** [comment]
I copied over the plugin.yml file from v4, which appears to have had the wrong usage for /bmclear. I've just pushed a possible fix for the deletion issue.
